# -*- coding: utf-8 -*-
"""Punto 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqUuUE_Ak1Joy_1-trdmiQ6fb6jOi1nY

#**2. Histéresis magnética**
"""

import pandas as pd
import re
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

# Leer el archivo CSV como texto
archivo = "/content/drive/MyDrive/Colab Notebooks/Métodos Computacionales 2/hysteresis.dat"

"""##**2.a. Datos**"""

filas = []
lista_1 = []
lista_2 = []
lista_3 = []
with open(archivo, "r") as file:
    for linea in file:
        patron = r'\b(\d{3})(\d\.)'
        linea = re.sub(patron, r'\1,\2', linea)
        linea = linea.replace(" ",",")
        linea = linea.replace("-",",-")
        elementos = linea.split(",")
        elementos = [elemento.strip() for elemento in elementos]
        lista_1.append(elementos[0])
        lista_2.append(elementos[1])
        lista_3.append(elementos[2])

tiempo = [float(num) for num in lista_1]
campo_externo = [float(num) for num in lista_2]
densidad_campo = [float(num) for num in lista_3]
print("Lista 1:", tiempo)
print("Lista 2:", campo_externo)
print("Lista 3:", densidad_campo)

plt.plot(tiempo, campo_externo, label='Campo Externo B [mT]', color='b')
plt.plot(tiempo, densidad_campo, label="Densidad de Campo Interno H [A/m]", color='r')


plt.xlabel('Tiempo [ms]')
plt.ylabel('B [mT] y H [A/m]')
plt.title('B,H vs. t')
plt.legend()
plt.grid()
plt.show()
plt.savefig("histérico.pdf", format="pdf")
plt.close()

"""##**2.b. Frecuencia de la señal**"""

time_seconds = [t / 1000 for t in tiempo]

peaks, _ = find_peaks(campo_externo, height=0)
peak_times = [time_seconds[i] for i in peaks]


if len(peak_times) > 1:
    periods = np.diff(peak_times)
    frequency = 1 / np.mean(periods)

    print(f"Frecuencia de oscilación de B: {frequency:.2f} Hz")
    print("Método: Se identificaron los picos de la señal B y se calculó el promedio de los períodos.")
else:
    print("No se encontraron suficientes picos para calcular la frecuencia.")

"""##**2.c. Energía perdida**"""

plt.plot(campo_externo, densidad_campo, label='Prueba', color='b')
plt.title('Histéresis magnética')
plt.xlabel('Campo Externo [mT]')
plt.ylabel('Densidad de Campo Interno [A/m]')
plt.grid()
plt.show()
plt.savefig("energy.pdf", format="pdf")
plt.close()

area = np.trapz(densidad_campo, campo_externo)
area= round(area,2)
print(f"Energía perdida por unidad de volumen: {area} J/m³")
